// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
// export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const CLOSE_FORM = 'CLOSE_FORM';
export const OPEN_FORM = 'OPEN_FORM';

export const SET_DISCUSS = 'SET_DISCUSS';
export const LOADING_DISCUSS = 'LOADING_DISCUSS';
export const DISCUSS_SET_ERRORS = 'DISCUSS_SET_ERROR';
export const DISCUSS_CLEAR_ERRORS = 'DISCUSS_CLEAR_ERRORS';

export const SET_RELATION = 'SET_RELATION';
export const LOADING_RELATION = 'LOADING_RELATION';
export const RELATION_SET_ERRORS = 'RELATION_SET_ERROR';
export const RELATION_CLEAR_ERRORS = 'RELATION_CLEAR_ERRORS';

export const SET_COMPANIES = 'SET_COMPANIES';
export const LOADING_COMPANIES = 'LOADING_COMPANIES';
export const COMPANIES_SET_ERRORS = 'COMPANIES_SET_ERROR';
export const COMPANIES_CLEAR_ERRORS = 'COMPANIES_CLEAR_ERRORS';

export const SET_SOCIAL = 'SET_SOCIAL';
export const LOADING_SOCIAL = 'LOADING_SOCIAL';
export const SOCIAL_SET_ERRORS = 'SOCIAL_SET_ERROR';
export const SOCIAL_CLEAR_ERRORS = 'SOCIAL_CLEAR_ERRORS';

export const PROFILE_SET_CREDENTIALS = 'PROFILE_SET_CREDENTIALS';
export const PROFILE_LOADING_CREDENTIALS = 'PROFILE_LOADING_CREDENTIALS';
export const PROFILE_SET_DISCUSS = 'PROFILE_SET_DISCUSS';
export const PROFILE_LOADING_DISCUSS = 'PROFILE_LOADING_DISCUSS';
export const PROFILE_SET_COMPANIES = 'PROFILE_SET_COMPANIES';
export const PROFILE_LOADING_COMPANIES = 'PROFILE_LOADING_COMPANIES';
export const PROFILE_SET_SOCIAL = 'PROFILE_SET_SOCIAL';
export const PROFILE_LOADING_SOCIAL = 'PROFILE_LOADING_SOCIAL';
export const PROFILE_SET_FOLLOWING = 'PROFILE_SET_FOLLOWING';
export const PROFILE_LOADING_FOLLOWING = 'PROFILE_LOADING_FOLLOWING';
export const PROFILE_SET_FOLLOWERS = 'PROFILE_SET_FOLLOWERS';
export const PROFILE_LOADING_FOLLOWERS = 'PROFILE_LOADING_FOLLOWERS';

export const PROFILE_SET_ERRORS = 'PROFILE_SET_ERROR';
export const PROFILE_CLEAR_ERRORS = 'PROFILE_CLEAR_ERRORS';

export const EXPLORE_SET_USER = 'EXPLORE_SET_USER';
export const EXPLORE_LOADING_USER = 'EXPLORE_LOADING_USER';
export const EXPLORE_SET_DISCUSS = 'EXPLORE_SET_DISCUSS';
export const EXPLORE_LOADING_DISCUSS = 'EXPLORE_LOADING_DISCUSS';
export const EXPLORE_SET_COMPANIES = 'EXPLORE_SET_COMPANIES';
export const EXPLORE_LOADING_COMPANIES = 'EXPLORE_LOADING_COMPANIES';
export const EXPLORE_SET_SOCIAL = 'EXPLORE_SET_SOCIAL';
export const EXPLORE_LOADING_SOCIAL = 'EXPLORE_LOADING_SOCIAL';

export const EXPLORE_SET_ERRORS = 'EXPLORE_SET_ERROR';
export const EXPLORE_CLEAR_ERRORS = 'EXPLORE_CLEAR_ERRORS';

// Data reducer types
// export const SET_POSTS = 'SET_POSTS';
// export const SET_POST = 'SET_POST';
// export const LIKE_POST = 'LIKE_POST';
// export const LIKING_POST = 'LIKING_POST';
// export const UNLIKE_POST = 'UNLIKE_POST';
// export const DELETE_POST = 'DELETE_POST';
// export const POST_POST = 'POST_POST';
// export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
// export const LIKE_COMMENT = 'LIKE_COMMENT';
// export const UNLIKE_COMMENT = 'UNLIKE_COMMENT';
// export const LIKING_COMMENT = 'LIKING_COMMENT';
// export const DELETE_COMMENT = 'DELETE_COMMENT';
// export const SET_CHNLS = 'SET_CHNLS';
// export const CREATE_CHANNEL = 'CREATE_CHANNEL';
// export const SET_SERVER = 'SET_SERVER';